   pipeline {
    agent { label 'agent-1' }

    stages {
        // stage('init') {
        //     steps {
        //         sh 'ls -ltr'
        //         sh 'pwd'
                
        //         sh '''
        //     cd roboshop-infra-standard/01-vpc
        //     terraform init
        // '''            
        // }
        //     }

        // stage('plan') {
        //     steps {
        //         sh '''
        //         cd roboshop-infra-standard/01-vpc
                
        //         terraform plan
        //         '''
                
        //     }
        // }
        // stage('Manual Approval') {
        //     steps {
        //         input message: 'Do you want to proceed with apply?', ok: 'Yes, Apply'
        //     }
        // }

        stage('destroy') {
            steps {
                sh '''
                cd roboshop-infra-standard/01-vpc
                terraform init -upgrade
               terraform destroy -auto-approve
               '''
            }
        }
    }
     post {
        always {
            echo 'This will always run (success or failure)'
        }
        success {
            echo 'This will run only if the pipeline succeeded from webhook'
        }
        failure {
            echo 'This will run only if the pipeline failed'
        }
        unstable {
            echo 'This will run if the build is unstable'
        }
        changed {
            echo 'This will run if the build status changed from the last run'
        }
        cleanup {
            echo 'This will run at the end for any necessary cleanup'
        }
    }
}


