   pipeline {
    agent { label 'agent-1' }

    stages {
        stage('init') {
            steps {
               sh 'terraform init'
            }
        }

        stage('plan') {
            steps {
                sh 'terraform plan'
                
            }
        }

        stage('apply') {
            steps {
               sh 'terraform apply -auto-aprove'
            }
        }
    }
     post {
        always {
            echo 'This will always run (success or failure)'
        }
        success {
            echo 'This will run only if the pipeline succeeded from webhook'
        }
        failure {
            echo 'This will run only if the pipeline failed'
        }
        unstable {
            echo 'This will run if the build is unstable'
        }
        changed {
            echo 'This will run if the build status changed from the last run'
        }
        cleanup {
            echo 'This will run at the end for any necessary cleanup'
        }
    }
}


